### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by Moleculor** [Xeio/VoidRewardParser#17] opened 2017-07-08 01:07 UTC
It crashes the moment I start it up, with or without Warframe running.

**Comment by Xeio** [comment] 2017-07-08 19:59
Yeah... so the problem is this depends on VoidGlitch's repository to function to fetch things like a list of prime items and ducat values, and that repository no longer exists.

I'm not sure it's worth the rewrite to that part at this point. Rarities and the # Owned are shown in-game now, so the only thing it really does extra is tries to fetch prices from Warframe.Market (though that's buggy at times anyway).

**Comment by f0nZ** [comment] 2017-08-25 16:02
Any idea how could we fix it?

**Comment by Moleculor** [comment] 2017-08-25 20:12
And if it is possible to fix, maybe it could be repurposed to indicate which items/relics are vaulted? That's the information I need these days.

**Comment by f0nZ** [comment] 2017-08-25 20:32
I got the fix, but unfortunately Tesseract can't read properbly brown/gold rarity primes.

The fix to atleast make it work, is just swaping a line at VoidRewardParser.exe.config

Check for the line that has MissionDecks.txt and swap the value for this one

https://raw.githubusercontent.com/RainingTerror7/WarframeData-master/master/MissionDecks.txt

**Comment by Xeio** [comment] 2017-08-25 22:50
You would need to find a new place to get prime data from (names of items, ducat counts, rarity) and change the https://github.com/Xeio/VoidRewardParser/blob/master/VoidRewardParser/Logic/PrimeData.cs file to correctly parse the new source of information.

**Comment by Moleculor** [comment] 2017-08-25 23:19
So, we'd need to parse this: https://n8k6e2y6.ssl.hwcdn.net/repos/hnfvc0o3jnfvc873njb03enrf56.html

**Comment by ghost** [comment] 2017-12-15 04:33
Anybody able to update the system that reads new parts?

**Comment by Xeio** [comment] 2017-12-16 23:48
Probably fixed now

**Closed as completed** 2017-12-16 23:48 UTC
